### ISSUE TITLE
Remove cbft-full version of Linux build

### ISSUE THREAD

**Issue by WillGardella** [couchbaselabs/cbft#189]
I believe the "full" version of the binaries no longer is needed. We should remove that and also remove the instructions from the getting started page that describe the differences between the two build versions.

https://github.com/couchbaselabs/cbft/releases/download/v0.3.1/cbft-full-v0.3.1-0-ga690828.linux.amd64.tar.gz

**Comment by steveyen** [comment]
fixed with commit b4007b8d, so the next dev preview release will no longer have cbft-full built.

**Comment by mschoch** [comment]
Not sure of the context, but a lot of languages we might want to support only appear in full.  We could make it less full though.

**Comment by mschoch** [comment]
Hey @steveyen and @WillGardella can we close the loop on this issue?

**Comment by steveyen** [comment]
Hi @mschoch & @WillGardella,

I'm going to propose a plan here, and consider this the current plan (unless I hear back that we're explicitly changing the plan).

The stance is that full-text cbft in V1 (watson) is going to be whatever we get from the non-ICU build.  On the one hand, all platforms should then be uniform and the same w.r.t. their level of language support.  None of this full-ish (foolish?) business :-)  So, there might be less initial headaches for tech support ("wait, so you're developing somehow on linux (where it works) but deploying on windows?").

On the other hand, that might not be many languages compared to what we want in the long term, but that's what I think of as the current plan.

**Comment by mschoch** [comment]
Cool, so I agree with that.  But, I think "full" is more than what you think.

Regarding ICU, I think we can safely omit that, it only adds support for Thai at the moment.

But, "full" also brings in support for libstemmer.  Libstemmer is still required for many European languages, like German.  The good news is that libstemmer is easily compiled and statically linked with the rest of Bleve.  The bad news is that since it's C, it still can't be done by Go's built-in cross-compilation.

For Couchbase Server this isn't a problem, we build Windows binaries on a Windows machine.  The problem right now is for the standalone developer previews which are built using Go's builtin cross compilation.
